language: generic

sudo: required

services:
	- docker


before_install:
	- docker build -t krishnadasar-sudheer-kumar/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true krishnadasar-sudheer-kumar/docker-react npm run test -- --coverage
